pub mod background_widget;
pub mod choord_widget;
pub mod completer_widget;
pub mod editor_widget;
pub mod info_line;
pub mod one_line_input_widget;
pub mod palette_widget;
pub mod search_widget;
pub mod splash;
