[package]
name = "ferrite-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cgmath = "0.18.0"
ferrite-cli = { workspace = true }
ferrite-core = { workspace = true }
ferrite-tui = { workspace = true }
ferrite-utility = { workspace = true }
glyphon = "0.7.0"
pollster = "0.3.0"
tracing = { workspace = true }
tui = { workspace = true, default-features = false }
unicode-width = { workspace = true }
wgpu = "23.0.0"
winit = "0.29.15"