theme = "default"
rulers = [80]
local_clipboard = false
show_splash = true
watch_recursive = true
watch_workspace = true
show_indent_rulers = false
always_prompt_on_exit = false
case_insensitive_search = true

[picker]
show_hidden = false
follow_gitignore = true
follow_git_exclude = true
follow_ignore = true
follow_git_global = true
show_only_text_files = true

[info_line]
left = ["size"]
center = ["file"]
right = ["branch", "position", "encoding", "language"]
padding = 1

[[language]]
name = "rust"
formatter = "rustfmt"

[[language]]
name = "cpp"
formatter = "clang-format"

[[language]]
name = "c"
formatter = "clang-format"
