theme = "default"
rulers = [80]
local_clipboard = false
show_splash = true
watch_open_files = true
show_indent_rulers = false
always_prompt_on_exit = false
case_insensitive_search = true
render_whitespace = "trailing"
line_number = "absolute"

[picker]
show_hidden = false
follow_gitignore = true
follow_git_exclude = true
follow_ignore = true
follow_git_global = true
show_only_text_files = true
file_picker_auto_reload = true

[info_line]
left = ["size"]
center = ["file"]
right = ["branch", "position", "encoding", "language", "spinner"]
padding = 1

[[language]]
name = "rust"
format = "rustfmt --edition 2021"

[[language]]
name = "cpp"
format = "clang-format"
format_selection = "clang-format --offset=%start% --length=%len%"

[[language]]
name = "c"
format = "clang-format"
format_selection = "clang-format --offset=%start% --length=%len%"