
[[language]]
name = "rust"
format = "rustfmt --edition 2024"

[[language]]
name = "json"
format = "jq"

[[language]]
name = "cpp"
format = "clang-format"
format_selection = "clang-format --offset=%start% --length=%len%"

[[language]]
name = "c"
format = "clang-format"
format_selection = "clang-format --offset=%start% --length=%len%"

[[language]]
name = "markdown"
auto_trim_whitespace = false
