[package]
name = "ferrite-git"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ferrite-utility = { workspace = true }
imara-diff = { workspace = true }
profiling = { workspace = true }
regex =  { workspace = true }
ropey = { workspace = true }
tracing = { workspace = true }
