"editor.line_nr" = { fg = "surface1", bg = "mantle" }
"editor.current_line_nr" = { fg = "text", bg = "mantle" }
"editor.text" = { fg = "text" }
"editor.info_line" = { fg = "subtext1", bg = "mantle" }
"editor.info_line.unfocused" = { fg = "surface1", bg = "mantle" }
"editor.background" = { fg = "text", bg = "base" }
"editor.selection" = { bg = "surface1"}
"editor.border" = { bg = "base", fg = "text" }
"editor.ruler" = { fg = "surface0" }
"editor.error_text" = { fg = "red" }
"editor.search.match" = { bg = "search_match" }
"editor.fuzzy.match" = { fg = "red" }
"editor.completer" = { bg = "surface1", fg = "text" }
"editor.completer.selected" = { bg = "surface1", fg = "text" }



[syntax]
"type" = { fg = "yellow" }

"constructor" = { fg = "sapphire" }

"constant" = { fg = "peach" }
"constant.builtin" = { fg = "peach" }
"constant.character" = { fg = "teal" }
"constant.character.escape" = { fg = "pink"}

"string" = { fg = "green" }
"string.regexp" = { fg = "peach" }
"string.special" = { fg = "blue" }

"comment" = { fg = "surface2" }
"info" = { fg = "yellow" }
"hint" = { fg = "yellow" }

"variable" = { fg = "text" }
"variable.parameter" = { fg = "maroon" }
"variable.builtin" = { fg = "red" }
"variable.other.member" = { fg = "teal" }

"label" = { fg = "sapphire" }

"punctuation" = { fg = "overlay2" }
"punctuation.special" = { fg = "sky" }

"keyword" = { fg = "mauve" }
"key" = { fg = "mauve" }

"operator" = { fg = "sky" }

"function" = { fg = "blue" }
"function.builtin" = { fg = "peach" }
"function.macro" = { fg = "mauve" }

"tag" = { fg = "mauve" }

"namespace" = { fg = "blue" }

"special" = { fg = "blue" }

# Special case for languages
"rust.type.builtin" = { fg = "yellow" } 

"markup.heading" = { fg = "lavender" }
"markup.raw" = { fg = "flamingo" }
"markup.bold" = { fg = "text" }
"markup.italic" = { fg = "teal" }
"markup.list" = { fg = "mauve" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "rosewater" }
"markup.link.text" = { fg = "blue" }

[palette]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"

text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"

base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

search_match = "#b4def1"