"editor.line_nr" = { fg = "base0", bg = "base02" }
"editor.current_line_nr" = { fg = "base3", bg = "base02" }
"editor.text" = { fg = "base1" }
"editor.dim_text" = { fg = "base1" }
"editor.info_line" = { fg = "base2", bg = "base02" }
"editor.info_line.unfocused" = { fg = "base0", bg = "base02" }
"editor.background" = { bg = "base03", fg = "base1" }
"editor.selection" = { bg = "base0175"}
"editor.border" = { bg = "base03", fg = "base1" }
"editor.pane_border" = { bg = "base03", fg = "base1" }
"editor.ruler" = { fg = "base02" }
"editor.error_text" = { fg = "red" }
"editor.search.match" = { bg = "base015" }
"editor.fuzzy.match" = { fg = "red" }
"editor.completer" = { bg = "base02", fg = "base1" }
"editor.completer.selected" = { bg = "base00", fg = "base03" }
"editor.cursorline" = { bg = "cursorline" }
"editor.scrollbar" = { bg = "base03", fg = "scrollbar" }

[syntax]
"text" = { fg = "base1" }
"attribute" = { fg = "violet" }
"key" = { fg = "green" }
"keyword" = { fg = "green" }
"keyword.directive" = { fg = "orange" }
"namespace" = { fg = "violet" }
"operator" = { fg = "green" }
"special" = { fg = "orange" }
"variable.builtin" = { fg = "cyan" }
"variable.function" = { fg = "blue" }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow" }
"constructor" = { fg = "blue" }
"function" = { fg = "blue" }
"function.macro" = { fg = "magenta" }
"function.builtin" = { fg = "blue" }
"function.special" = { fg = "magenta" }
"comment" = { fg = "base01" }
"info" = { fg = "yellow" }
"hint" = { fg = "yellow" }
"string" = { fg = "cyan" }
"constant" = { fg = "cyan" }
"constant.builtin" = { fg = "cyan" }
"constant.character.escape" = { fg = "red" }
"label" = { fg = "green" }
"module" = { fg = "violet" }
"tag" = { fg = "magenta" }
"variable" =  { fg = "base1" }
"variable.other.member" = { fg = "magenta" }
"punctuation" = { fg = "base1" }
"markup.heading" = { fg = "blue" }
"markup.list" = { fg = "red" }
"markup.bold" = { fg = "yellow" }
"markup.italic" = { fg = "magenta" }
"markup.link.url" = { fg = "yellow" }
"markup.link.text" = { fg = "red" }
"markup.quote" = { fg = "cyan" }
"markup.raw" = { fg = "green" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }

[palette]
red      = "#dc322f"
green    = "#859900"
yellow   = "#b58900"
blue     = "#268bd2"
magenta  = "#d33682"
cyan     = "#2aa198"
orange   = "#cb4b16"
violet   = "#6c71c4"

# dark getting darker
base0    = "#657b83"
base1    = "#586e75"
base2    = "#073642"
base3    = "#002b36"

# Lighter and lighter
base00    = "#839496"
base01    = "#93a1a1"
base015   = "#c5c8bd"
base0175  = "#dddbcc"
base02    = "#eee8d5"
base025   = "#f5eedb"
base03    = "#fdf6e3"

cursorline = "#eee8d5"
scrollbar = "#c0bcb0"