#[cfg(feature = "lang-bash")]
pub use tree_sitter_bash;
#[cfg(feature = "lang-c")]
pub use tree_sitter_c;
#[cfg(feature = "lang-c-sharp")]
pub use tree_sitter_c_sharp;
#[cfg(feature = "lang-cmake")]
pub use tree_sitter_cmake;
#[cfg(feature = "lang-comment")]
pub use tree_sitter_comment;
#[cfg(feature = "lang-cpp")]
pub use tree_sitter_cpp;
#[cfg(feature = "lang-css")]
pub use tree_sitter_css;
#[cfg(feature = "lang-fish")]
pub use tree_sitter_fish;
#[cfg(feature = "lang-fortran")]
pub use tree_sitter_fortran;
#[cfg(feature = "lang-glsl")]
pub use tree_sitter_glsl;
#[cfg(feature = "lang-go")]
pub use tree_sitter_go;
#[cfg(feature = "lang-html")]
pub use tree_sitter_html;
#[cfg(feature = "lang-hyprlang")]
pub use tree_sitter_hyprlang;
#[cfg(feature = "lang-ini")]
pub use tree_sitter_ini;
#[cfg(feature = "lang-javascript")]
pub use tree_sitter_javascript;
#[cfg(feature = "lang-json")]
pub use tree_sitter_json;
#[cfg(feature = "lang-md")]
pub use tree_sitter_md;
#[cfg(feature = "lang-python")]
pub use tree_sitter_python;
#[cfg(feature = "lang-ron")]
pub use tree_sitter_ron;
#[cfg(feature = "lang-rust")]
pub use tree_sitter_rust;
#[cfg(feature = "lang-toml")]
pub use tree_sitter_toml;
#[cfg(feature = "lang-typescript")]
pub use tree_sitter_typescript;
#[cfg(feature = "lang-xml")]
pub use tree_sitter_xml;
#[cfg(feature = "lang-yaml")]
pub use tree_sitter_yaml;
#[cfg(feature = "lang-zig")]
pub use tree_sitter_zig;
