use core::fmt;
use std::path::PathBuf;

use ferrite_utility::{line_ending::LineEnding, point::Point};
use serde::{Deserialize, Serialize};

use crate::{buffer::case::Case, layout::panes::Direction};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum LineMoveDir {
    Up,
    Down,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "cmd", rename_all = "snake_case")]
pub enum Cmd {
    Nop,
    OpenFile {
        path: PathBuf,
    },
    Cd {
        path: PathBuf,
    },
    Save {
        path: Option<PathBuf>,
    },
    Language {
        language: Option<String>,
    },
    Encoding {
        encoding: Option<String>,
    },
    LineEnding {
        line_ending: Option<LineEnding>,
    },
    RunShellCmd {
        args: Vec<PathBuf>,
        pipe: bool,
    },
    OpenShellPalette,
    Case {
        case: Case,
    },
    Split {
        direction: Direction,
    },
    ReplaceAll {
        text: String,
    },
    Replace,
    Search,
    About,
    Path,
    Pwd,
    New {
        path: Option<PathBuf>,
    },
    Reload,
    ReloadAll,
    Logger,
    ForceQuit,
    Quit,
    UrlOpen,
    Goto {
        line: i64,
    },
    Indent {
        indent: Option<String>,
    },
    Theme {
        theme: Option<String>,
    },
    SortLines {
        ascending: bool,
    },
    BufferPickerOpen,
    FilePickerOpen,
    FilePickerReload,
    OpenConfig,
    DefaultConfig,
    OpenLanguages,
    DefaultLanguages,
    OpenKeymap,
    DefaultKeymap,
    ForceClose,
    Close,
    ClosePane,
    Paste,
    Copy,
    Format,
    FormatSelection,
    GitReload,
    RevertBuffer,
    Trash,
    Repeat,
    MoveRight {
        expand_selection: bool,
    },
    MoveLeft {
        expand_selection: bool,
    },
    MoveUp {
        expand_selection: bool,
        create_cursor: bool,
        distance: usize,
    },
    MoveDown {
        expand_selection: bool,
        create_cursor: bool,
        distance: usize,
    },
    MoveRightWord {
        expand_selection: bool,
    },
    MoveLeftWord {
        expand_selection: bool,
    },
    Insert {
        text: String,
    },
    Char {
        ch: char,
    },
    MoveLine {
        direction: LineMoveDir,
    },
    Backspace,
    BackspaceWord,
    BackspaceToStartOfLine,
    Delete,
    DeleteWord,
    DeleteToEndOfLine,
    ClickCell {
        spawn_cursor: bool,
        column: usize,
        line: usize,
    },
    SelectArea {
        cursor: Point<usize>,
        anchor: Point<usize>,
    },
    PromptGoto,
    Home {
        expand_selection: bool,
    },
    End {
        expand_selection: bool,
    },
    Eof {
        expand_selection: bool,
    },
    Start {
        expand_selection: bool,
    },
    SelectAll,
    SelectLine,
    SelectWord,
    RemoveLine,
    Cut,
    PastePrimary {
        column: usize,
        line: usize,
    },
    TabOrIndent {
        back: bool,
    },
    Undo,
    Redo,
    VerticalScroll {
        distance: i64,
    },
    ReplaceCurrentMatch,
    GlobalSearch,
    CaseInsensitive,
    NextMatch,
    PrevMatch,
    FocusPalette,
    OpenFilePicker,
    OpenBufferPicker,
    Escape,
    SaveAll,
    GrowPane,
    ShrinkPane,
    InputMode {
        name: String,
    },
    ReopenBuffer,
    RotateFile,
    ForceRedraw,
    SwitchPane {
        direction: Direction,
    },
    Number {
        start: Option<i64>,
    },
    OpenFileExplorer {
        path: Option<PathBuf>,
    },
    TrimTrailingWhitespace,
    ZoomIn,
    ZoomOut,
    ResetZoom,
    KillJob,
    RunAction {
        name: String,
    },
    NewLineWithoutBreaking,
    NewLineAboveWithoutBreaking,
    SelectAllMatching,
}

impl Cmd {
    fn as_str(&self) -> &str {
        use Cmd::*;
        match self {
            Nop => "Nop",
            Repeat { .. } => "Repeat",
            MoveRight { .. } => "Move right",
            MoveLeft { .. } => "Move left",
            MoveUp { .. } => "Move up",
            MoveDown { .. } => "Move down",
            MoveRightWord { .. } => "Move right word",
            MoveLeftWord { .. } => "Move left word",
            Insert { text } => text.as_str(),
            Char { .. } => "char",
            MoveLine {
                direction: LineMoveDir::Up,
            } => "Move line up",
            MoveLine {
                direction: LineMoveDir::Down,
            } => "Move line down",
            Backspace => "Backspace",
            BackspaceWord => "Backspace word",
            BackspaceToStartOfLine => "Backspace to start of line",
            Delete => "Delete",
            DeleteWord => "Delete word",
            DeleteToEndOfLine => "Delete to end of line",
            ClickCell { .. } => "Set cursor pos",
            SelectArea { .. } => "Select area",
            PromptGoto => "Goto",
            Home { .. } => "Home",
            End { .. } => "End",
            Eof { .. } => "End of file",
            Start { .. } => "Start",
            SelectAll => "Select all",
            SelectLine => "Select line",
            RemoveLine => "Remove line",
            SelectWord => "Select word",
            Copy => "Cpy",
            Cut => "Cut",
            Paste => "Paste",
            PastePrimary { .. } => "Paste primary",
            TabOrIndent { .. } => "TabOrIndent",
            Undo => "Undo",
            Redo => "Redo",
            RevertBuffer => "Revert buffer",
            VerticalScroll { .. } => "Vertical scroll",
            Search => "Search file",
            Replace => "Replace",
            ReplaceCurrentMatch => "Replace current match",
            GlobalSearch => "Global workspace search",
            CaseInsensitive => "Case insensitive",
            NextMatch => "Next match",
            PrevMatch => "Prev match",
            FocusPalette => "Open palette",
            OpenFilePicker => "Open file picker",
            OpenBufferPicker => "Open buffer picker",
            Escape => "Escape",
            SaveAll => "SaveAll",
            Quit => "Quit",
            Close => "Close buffer",
            ClosePane => "Close pane",
            GrowPane => "Grow pane",
            ShrinkPane => "Shrink pane",
            InputMode { name } => name,
            Format => "Format",
            UrlOpen => "Open urls in selection",
            Split {
                direction: Direction::Right,
            } => "Split right",
            Split {
                direction: Direction::Left,
            } => "Split left",
            Split {
                direction: Direction::Up,
            } => "Split up",
            Split {
                direction: Direction::Down,
            } => "Split down",
            ReopenBuffer => "Reopen buffer",
            New { .. } => "New",
            RotateFile => "Rotate file",
            OpenFile { .. } => "Open file",
            Cd { .. } => "Change project directory",
            Save { .. } => "Save buffer",
            Language { .. } => "Language",
            Encoding { .. } => "Encoding",
            LineEnding { .. } => "Line ending",
            RunShellCmd { .. } => "Run shell command",
            OpenShellPalette { .. } => "Open shell command palette",
            Case { .. } => "Case",
            ReplaceAll { .. } => "Replace all",
            About => "About",
            Path => "Show filepath",
            Pwd => "Print working directory",
            Reload => "Reload",
            ReloadAll => "Reload all buffers",
            Logger => "Logger",
            ForceQuit => "Force quit",
            Goto { .. } => "Goto",
            Indent { .. } => "Indent",
            Theme { .. } => "Theme",
            SortLines { .. } => "Sort lines",
            BufferPickerOpen => "Open buffer picker",
            FilePickerOpen => "Open file picker",
            FilePickerReload => "Reload file picker",
            OpenConfig => "Open editor config file",
            DefaultConfig => "Open default editor config",
            OpenLanguages => "Open languages config file",
            DefaultLanguages => "Open default languages config",
            OpenKeymap => "Open keymap config file",
            DefaultKeymap => "Open default keymap",
            ForceClose => "Force close buffer",
            FormatSelection => "Format selection",
            GitReload => "Git reload",
            Trash => "Move to trash",
            ForceRedraw => "Force redraw",
            SwitchPane { direction } => match direction {
                Direction::Up => "Up pane",
                Direction::Down => "Down pane",
                Direction::Right => "Right pane",
                Direction::Left => "Left pane",
            },
            Number { .. } => "Number",
            OpenFileExplorer { .. } => "Open file explorer",
            TrimTrailingWhitespace => "Trim trailing whitespace",
            ZoomIn => "Zoom in",
            ZoomOut => "Zoom out",
            ResetZoom => "Reset zoom",
            KillJob => "Kill job",
            RunAction { .. } => "Run",
            NewLineWithoutBreaking => "Insert new line without breaking",
            NewLineAboveWithoutBreaking => "Insert new line above without breaking",
            SelectAllMatching => "Select all matching",
        }
    }

    pub fn is_repeatable(&self) -> bool {
        use Cmd::*;
        match self {
            Nop => false,
            Repeat => false,
            MoveRight { .. } => true,
            MoveLeft { .. } => true,
            MoveUp { .. } => true,
            MoveDown { .. } => true,
            MoveRightWord { .. } => true,
            MoveLeftWord { .. } => true,
            Insert { .. } => true,
            Char { .. } => true,
            MoveLine { .. } => true,
            Backspace => true,
            BackspaceWord => true,
            BackspaceToStartOfLine => true,
            Delete => true,
            DeleteWord => true,
            DeleteToEndOfLine => true,
            ClickCell { .. } => false,
            SelectArea { .. } => false,
            PromptGoto => false,
            Home { .. } => true,
            End { .. } => true,
            Eof { .. } => false,
            Start { .. } => false,
            SelectAll => false,
            SelectLine => true,
            SelectWord => true,
            RemoveLine => true,
            Copy => false,
            Cut => false,
            Paste => true,
            PastePrimary { .. } => true,
            TabOrIndent { .. } => true,
            Undo => true,
            Redo => true,
            RevertBuffer => false,
            VerticalScroll { .. } => true,
            Search => false,
            Replace => false,
            ReplaceCurrentMatch => true,
            GlobalSearch => false,
            CaseInsensitive => false,
            NextMatch => true,
            PrevMatch => true,
            FocusPalette => false,
            OpenFilePicker => false,
            OpenBufferPicker => false,
            Escape => false,
            SaveAll => false,
            Quit => false,
            Close => false,
            ClosePane => false,
            GrowPane => true,
            ShrinkPane => true,
            InputMode { .. } => false,
            Format => false,
            RunShellCmd { .. } => false,
            OpenShellPalette { .. } => false,
            Split { .. } => false,
            ReopenBuffer => false,
            RotateFile => false,
            OpenFile { .. } => false,
            Cd { .. } => false,
            Save { .. } => false,
            Language { .. } => false,
            Encoding { .. } => false,
            LineEnding { .. } => false,
            Case { .. } => false,
            ReplaceAll { .. } => false,
            About => false,
            Path => false,
            Pwd => false,
            New { .. } => false,
            Reload => false,
            ReloadAll => false,
            Logger => false,
            ForceQuit => false,
            UrlOpen => false,
            Goto { .. } => false,
            Indent { .. } => false,
            Theme { .. } => false,
            SortLines { .. } => false,
            BufferPickerOpen => false,
            FilePickerOpen => false,
            FilePickerReload => false,
            OpenConfig => false,
            DefaultConfig => false,
            OpenLanguages => false,
            DefaultLanguages => false,
            OpenKeymap => false,
            DefaultKeymap => false,
            ForceClose => false,
            FormatSelection => false,
            GitReload => false,
            Trash => false,
            ForceRedraw => false,
            SwitchPane { .. } => false,
            Number { .. } => false,
            OpenFileExplorer { .. } => false,
            TrimTrailingWhitespace => false,
            ZoomIn => false,
            ZoomOut => false,
            ResetZoom => false,
            KillJob => false,
            RunAction { .. } => true,
            NewLineWithoutBreaking => true,
            NewLineAboveWithoutBreaking => true,
            SelectAllMatching => false,
        }
    }
}

impl fmt::Display for Cmd {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_str().fmt(f)
    }
}
