name: Rust

on: [push]

jobs:
  vendor-sources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Vendor
        run: |
          mkdir -p .cargo
          cargo vendor > .cargo/config.toml
      - name: Package all sources
        run: tar -czvf ferrite-vendored-source.tar.gz *
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vendored-source
          path: ferrite-vendored-source.tar.gz

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Vendor
        run: cargo vendor
      - name: Build
        run: cargo build --release --all-features
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ubuntu-build-artifacts
          path: target/release/ferrite

  build-linux-musl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install system deps
        run: cargo install cross
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Vendor
        run: cargo vendor
      - name: Build
        run: cross build --target=x86_64-unknown-linux-musl --release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ubuntu-musl-build-artifacts
          path: target/x86_64-unknown-linux-musl/release/ferrite

  build-linux-aarch64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install system deps
        run: cargo install cross
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Vendor
        run: cargo vendor
      - name: Build
        run: cross build --target=aarch64-unknown-linux-gnu --release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: aarch-linux-build-artifacts
          path: target/x86_64-unknown-linux-musl/release/ferrite

  build-linux-old-glibc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Docker build
        run: |
          rm .cargo/config.toml
          ./build_in_container.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ubuntu-old-glibc-build-artifacts
          path: ferrite

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Vendor
        run: cargo vendor
      - name: Build
        run: cargo build --release --all-features
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-build-artifacts
          path: target/release/ferrite.exe
